# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b454f757ece2f6bc2afaa3d01930059bf9c163ff73860dfbe85beb16acd74c6c6f552a60c8cdb097f31313f0ece483d55afdabf98faf19cd5766e3e9fa2711f4

test:
  secret_key_base: 94befd0476c02567f7a3c1f1de89581e311b2fb6971ba3e8e9e4bc53f989ac8822eb372612e1c54a898910b0cbf394d339a0670886c2132c2c507cb186892d44

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
